apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: cep-project1
type: Opaque
data:
  mysql-root-password: cm9vdAo= #<base64-encoded-root-password>
  mysql-password: cm9vdAo=   #<base64-encoded-password>
